compile:
	g++ T1.cpp -o t1.out
	g++ T2.cpp -o t2.out
	g++ T4.cpp -o t4.out
	g++ T5.cpp -o t5.out
	g++ T8.cpp -o t8.out
	g++ T10.cpp -o t10.out
	g++ T12.cpp -o t12.out
	g++ T13.cpp -o t13.out
	g++ T14.cpp -o t14.out
	g++ T16.cpp -o t16.out
	g++ T18.cpp -o t18.out
	g++ T20.cpp -o t20.out
	g++ T22.cpp -o t22.out
run:
	./t1.out
	./t2.out
	./t4.out
	./t5.out
	./t8.out
	./t10.out
	./t12.out
	./t13.out
	./t14.out
	./t16.out
	./t18.out
	./t20.out
	./t22.out
debug:
	lldb ./t1.out